title: Il nostro blog ITPUG - ITalian PostgreSQL Users Group
email: info@itpug.org
description: > # this means to ignore newlines until "baseurl:"
  ITPUG - Italian PostgreSQL Users Group è una associazione no-profit per la promozione, divulgazione e la tutela del Software Libero (FLOSS) in Italia.
  In modo particolare, l'associazione ITPUG promuove l'adozione  di PostgreSQL (http://www.postgresql.org), uno dei progetti open source di maggior successo.

permalink: ':title/'
baseurl: "/blog.itpug.org" # the subpath of your site, e.g. /blog
url: "https://itpug.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: ITPUG - ITalian PostgreSQL Users Group # add your name
author-pic: itpug_logo125.jpg
about-author: ITPUG - Italian PostgreSQL Users Group è una associazione no-profit per la promozione, divulgazione e la tutela del Software Libero (FLOSS) in Italia.
    In modo particolare, l'associazione ITPUG promuove l'adozione  di PostgreSQL (http://www.postgresql.org), uno dei progetti open source di maggior successo.

# Contact links
email: info@itpug.org # Add your Email address
# phone: # Add your Phone number
website: www.itpug.org/index.it.html # Add your website, do not add http://
linkedin: 11134629/ # Add your Linkedin handle
github: ITPUG # Add your Github handle
twitter: '@ITPUGPRESS' # Add your Twitter handle
facebook: # Add your Facebook handle
flickr: photos/itpug/ # Add your flickr handle
# pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
